"""Create initial migrations

Revision ID: 8b1baef54852
Revises: 
Create Date: 2024-11-11 12:50:03.770727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from vintasend_sqlalchemy.alembic_initial_migration_ops import create_notification_table


# revision identifiers, used by Alembic.
revision: str = '8b1baef54852'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    create_notification_table(sa.Integer)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
