name: CI

on: [push, pull_request]

jobs:
  build-python:
    name: CI (Python ${{ matrix.python-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: vintasoftware/vintasend-sqlalchemy
          fail_ci_if_error: false
          directory: ./
          files: ./coverage-*.xml
          flags: python-${{ matrix.python-version }}
          name: codecov-${{ matrix.python-version }}
