name: CI

on: [push, pull_request]

jobs:
  build-python:
    name: CI (Python ${{ matrix.python-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run tox
        env:
          OPENAI_API_KEY: "sk-fake-test-key-123"

      - name: Coveralls Parallel
        run: |
          poetry run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: "github-actions"
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_FLAG_NAME: python-coverage-${{ matrix.python-version }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Coveralls

    # Wait for Django and Frontend to finish before starting due to Coveralls parallel
    needs: [build-python]

    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          carryforward: "python-coverage-3.10,python-coverage-3.11,python-coverage-3.12,python-coverage-3.13"